config/routes.rb
Srmatham::Application.routes.draw do
  get "home/index"

  resources :seva_bookings do
    get :eodreport, :on=>:collection
    get :eodreport_print, :on=>:collection
    get :date_range_report, :on=>:collection
    get :date_range_report_print, :on=> :collection
    get :seva_report, :on=>:collection
    get :seva_report_print, :on=>:collection
    get :get_persons, :on=>:collection
    get :print, :on => :member
    post :save_reciept
    get :grt, :on=>:collection
    get :othereodreport, :on=>:collection
    get :othereodreport_print, :on=>:collection
end

  resources :sevas do
    get :sevareport, :on=>:collection
  end

  resources :gotrams

  root :to => "home#index"

   match ':controller(/:action(/:id(.:format)))'
end

app/models/gotram.rb
class Gotram < ActiveRecord::Base
    has_many :seva_bookings
    validates_uniqueness_of :name
end

app/controllers/gotrams_controller.rb
class GotramsController < ApplicationController
  # GET /gotrams
  # GET /gotrams.xml
  def index
    @gotrams = Gotram.order("name ASC")

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @gotrams }
    end
  end

  # GET /gotrams/1
  # GET /gotrams/1.xml
  def show
    @gotram = Gotram.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @gotram }
    end
  end

  # GET /gotrams/new
  # GET /gotrams/new.xml
  def new
    @gotram = Gotram.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @gotram }
    end
  end

  # GET /gotrams/1/edit
  def edit
    @gotram = Gotram.find(params[:id])
  end

  # POST /gotrams
  # POST /gotrams.xml
  def create
    @gotram = Gotram.new(params[:gotram])

    respond_to do |format|
      if @gotram.save
        format.html { redirect_to(@gotram, :notice => 'Gotram was successfully created.') }
        format.xml  { render :xml => @gotram, :status => :created, :location => @gotram }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @gotram.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /gotrams/1
  # PUT /gotrams/1.xml
  def update
    @gotram = Gotram.find(params[:id])

    respond_to do |format|
      if @gotram.update_attributes(params[:gotram])
        format.html { redirect_to(@gotram, :notice => 'Gotram was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @gotram.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /gotrams/1
  # DELETE /gotrams/1.xml
  def destroy
    @gotram = Gotram.find(params[:id])
    @gotram.destroy

    respond_to do |format|
      format.html { redirect_to(gotrams_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/gotrams_helper.rb
module GotramsHelper
end

app/views/gotrams/_form.html.erb
<%= form_for(@gotram) do |f| %>
  <% if @gotram.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gotram.errors.count, "error") %> prohibited this gotram from being saved:</h2>

      <ul>
      <% @gotram.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name ,:id=>'dname',:onChange=>"capitalizeMe(this)"%>
	    <script type="text/javascript">
        var dname = new LiveValidation('dname');
        dname.add(Validate.Presence)
    </script>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description,:cols => 30, :rows => 5 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gotrams/edit.html.erb
<h3>Edit Gotram</h3>
<hr />

<%= render 'form' %>

<%= link_to 'Show', @gotram %> 
<%= link_to 'Back', gotrams_path %>

app/views/gotrams/index.html.erb
<center>
<%= link_to 'New Gotram', new_gotram_path %> <br /><br />
<table id='listGotrams'>
  <thead>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>

  </tr>
  </thead>
  <tbody>
<% @gotrams.each do |gotram| %>
  <tr>
    <td><%= gotram.name %></td>
    <td><%= gotram.description %></td>
    <td><%= link_to 'Show', gotram %></td>
    <td><%= link_to 'Edit', edit_gotram_path(gotram) %></td>
<!--     <td><%= link_to 'Destroy', gotram, :confirm => 'Are you sure?', :method => :delete %></td> -->
  </tr>
<% end %>
  </tbody>
</table>
</center>
<br />


<script>
$('#listGotrams').fixheadertable({
    caption     : 'List Gotrams',
    colratio    : [150, 650],
    height      : 200,
    width       : 800,
    zebra       : false,
    sortable    : true,
    sortedColId : 1,
    sortType    : ['string', 'string'],
    dateFormat  : 'm/d/Y',
    pager       : true,
    rowsPerPage : 10,
    resizeCol	: true
});
</script>

app/views/gotrams/new.html.erb
<h3>New Gotram</h3>
<hr />

<%= render 'form' %>
<%= link_to 'Back', gotrams_path %>

app/views/gotrams/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @gotram.name %>
</p>

<p>
  <b>Description:</b>
  <%= @gotram.description %>
</p>

<%= link_to 'Edit', edit_gotram_path(@gotram) %> 
<%= link_to 'Back', gotrams_path %>