config/routes.rb
Srmatham::Application.routes.draw do
  get "home/index"

  resources :seva_bookings do
    get :eodreport, :on=>:collection
    get :eodreport_print, :on=>:collection
    get :date_range_report, :on=>:collection
    get :date_range_report_print, :on=> :collection
    get :seva_report, :on=>:collection
    get :seva_report_print, :on=>:collection
    get :get_persons, :on=>:collection
    get :print, :on => :member
    post :save_reciept
    get :grt, :on=>:collection
    get :othereodreport, :on=>:collection
    get :othereodreport_print, :on=>:collection
end

  resources :sevas do
    get :sevareport, :on=>:collection
  end

  resources :gotrams

  root :to => "home#index"

   match ':controller(/:action(/:id(.:format)))'
end

app/models/seva_booking.rb
class SevaBooking < ActiveRecord::Base
  belongs_to :gotram
  belongs_to :seva
  validates_presence_of :devotee_name
end

app/controllers/seva_bookings_controller.rb
class SevaBookingsController < ApplicationController
  layout 'application', :except => :print
  def index
    @seva_bookings = SevaBooking.order("reciept_number ASC, booking_date DESC")
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @seva_bookings }
    end
  end
  
  def show
    @seva_booking = SevaBooking.find(params[:id])
    
    respond_to do |format|
      format.html # show.html.erb
      
    end
  end
  
  
  def print
    @seva_booking = SevaBooking.find(params[:id])
=begin
    #PDF Render   
    html = render_to_string :layout => false 
    kit = PDFKit.new(html)
#    kit.stylesheets << RAILS_ROOT + '/public/stylesheets/screen.css' 
    send_data(kit.to_pdf, :filename => "Reciept-#{params[:id]}.pdf", :type => 'application/pdf')
=end
  end
  
  def new
    @seva_booking = SevaBooking.new
    @gotrams = Gotram.order("name ASC")
    @sevas = Seva.order("name ASC")
    
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @seva_booking }
    end
  end
  
  def edit
    @seva_booking = SevaBooking.find(params[:id])
    @gotrams = Gotram.all
    @sevas = Seva.all
    
  end
  
  def create
    @seva_booking = SevaBooking.new(params[:seva_booking])
    #Increment seva_number in sevas
    seva =Seva.find(params[:seva_booking][:seva_id])
    seva.increment!(:seva_number)
    @seva_booking.reciept_number = seva.short_code + "%05d" % seva.seva_number
    
    if @seva_booking.seva.name="Others"
      @seva_booking.amount = params[:seva_booking][:amount]
      #      puts"########################"
      @seva_booking.amount
    else
      @seva_booking.amount = @seva_booking.seva.rate
      #      puts"########################"
      @seva_booking.amount
    end
    
    respond_to do |format|
      if @seva_booking.save
        format.html { redirect_to(@seva_booking, :notice => 'Seva Booking was successfully created.') }
        format.xml  { render :xml => @seva_booking, :status => :created, :location => @seva_booking }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @seva_booking.errors, :status => :unprocessable_entity }
      end
    end
    
  end
  
  def update
    @seva_booking = SevaBooking.find(params[:id])
    @seva_booking.amount = params[:seva_booking]? params[:seva_booking]:@seva_booking.seva.rate
    respond_to do |format|
      if @seva_booking.update_attributes(params[:seva_booking])
        format.html { redirect_to(@seva_booking, :notice => 'Seva Booking was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @seva_booking.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @seva_booking = SevaBooking.find(params[:id])
    @seva_booking.destroy
    
    respond_to do |format|
      format.html { redirect_to(seva_bookings_url) }
      format.xml  { head :ok }
    end
  end
  
  def eodreport
    @sevas = Seva.includes([:seva_bookings]).where("seva_bookings.booking_date=?",Date.today).order(:name)
    respond_to do |format|
      format.html
    end
    
    
  end
  
  def eodreport_print
    # @eodreport = SevaBooking.where(:booking_date => Date.today)
    @sevas = Seva.includes([:seva_bookings]).where("seva_bookings.booking_date=?",Date.today).order(:name)
    #PDF Render   
    html = render_to_string :layout => false 
    kit = PDFKit.new(html)
    kit.stylesheets << RAILS_ROOT + '/public/stylesheets/styles.css' 
    send_data(kit.to_pdf, :filename => "labels.pdf", :type => 'application/pdf')
    
  end
  
  def date_range_report
    if params[:start_date] == nil && params[:end_date] == nil
      @rangereport = []
    else
      @rangereport = SevaBooking.where(:seva_date => params[:start_date].to_date..params[:end_date].to_date)
    end
    
    respond_to do |format|
      format.html
    end
  end
  
  def date_range_report_print   
    if params[:start_date] == nil && params[:end_date] == nil
      @sevas = []
    else
      @sevas = Seva.includes([:seva_bookings]).where("seva_bookings.seva_date>=? AND seva_bookings.seva_date<=?" ,params[:start_date].to_date,params[:end_date].to_date).order(:name)
    end
    #      @sevas = Seva.includes([:seva_bookings]).where("seva_bookings.seva_date>=? AND seva_bookings.seva_date<=?" ,params[:start_date].to_date,params[:end_date].to_date).order(:name)
    
    html = render_to_string :layout => false 
    kit = PDFKit.new(html)
    kit.stylesheets << RAILS_ROOT + '/public/stylesheets/styles.css' 
    send_data(kit.to_pdf, :filename => "Seva_Report.pdf", :type => 'application/pdf')
    
    
  end
  
  def seva_report
    #    @sevareport = SevaBooking.find(:all, :conditions=>{:seva_date => Date.today})
    if params[:start_date] == nil && params[:end_date] == nil
      @rangereport = []
    else
      @rangereport = SevaBooking.where(:booking_date => params[:start_date].to_date..params[:end_date].to_date)
    end
    respond_to do |format|
      format.html
     
    end
  end
  
  def seva_report_print
    @sevas = Seva.includes([:seva_bookings]).where("seva_bookings.booking_date" => params[:start_date].to_date..params[:end_date].to_date).order("name")
    
    html = render_to_string :layout => false 
    kit = PDFKit.new(html)
    kit.stylesheets << RAILS_ROOT + '/public/stylesheets/styles.css' 
    send_data(kit.to_pdf, :filename => "Date_Range_Report.pdf", :type => 'application/pdf')
  end
  
  def get_persons
    @seva = Seva.find(params[:id])
    
    respond_to do |format|
      format.js
    end
  end
  
  def save_reciept
    @seva_booking = SevaBooking.find(params[:seva_booking_id])
    @seva_booking.reciept_number = params[:reciept_number]
    @seva_booking.save
    respond_to do |format|
      format.js
    end
    
  end
  
  def grt
    @seva_booking = SevaBooking.new
    @gotrams = Gotram.order("name ASC")
    @sevas = Seva.order("name ASC")
    
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @seva_booking }
    end
  end
  
  def othereodreport
    @eodreport = SevaBooking.find(:all,:conditions=>{:booking_date=>Date.today, :seva_id=>36},:order => "reciept_number DESC")  
  end
  def othereodreport_print
    @eodreport = SevaBooking.find(:all,:conditions=>{:booking_date=>Date.today, :seva_id=>36},:order => "reciept_number ASC") 
    html = render_to_string :layout => false 
    kit = PDFKit.new(html)
    kit.stylesheets << RAILS_ROOT + '/public/stylesheets/styles.css' 
    send_data(kit.to_pdf, :filename => "OtherEDDReport.pdf", :type => 'application/pdf')
  end
end

app/helpers/seva_bookings_helper.rb
module SevaBookingsHelper
end

app/views/seva_bookings/_form.html.erb
<%= form_for(@seva_booking) do |f| %>
  <% if @seva_booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@seva_booking.errors.count, "error") %> prohibited this seva_booking from being saved:</h2>

      <ul>
      <% @seva_booking.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :devotee_name ,"Devotee Name" %><br />
    <%= f.text_field :devotee_name,:id=>'dname',:onChange=>"capitalizeMe(this)" %>
	<script type="text/javascript">
				var dname = new LiveValidation('dname');
				dname.add(Validate.Presence)
	</script>
  </div>
  <div class="field">
    <%= f.label :gotram %><br />
    <%= collection_select(:seva_booking, :gotram_id, @gotrams, :id, :name, :prompt=> "Select Gotram") %>
		<script type="text/javascript">
				var seva_booking_gotram_id = new LiveValidation('seva_booking_gotram_id');
				seva_booking_gotram_id.add(Validate.Presence)
	</script>
  </div>
      <div class="field" style="display:none" id="gotram_name">
    <%= f.label :gotram %><br />
    <%= f.text_field :gotram_name,:onChange=>"capitalizeMe(this)" %>
  </div>

  <div class="field">
    <%= f.label :seva %><br />
    <%= collection_select(:seva_booking, :seva_id, @sevas, :id, :name, :prompt=> "Select Seva") %>
		<script type="text/javascript">
				var seva_booking_seva_id = new LiveValidation('seva_booking_seva_id');
				seva_booking_seva_id.add(Validate.Presence)
	</script>
  </div>
  <div class="field">
    <%= f.label :seva_date, "Seva Date" %><br />
    <%= f.date_select :seva_date,:start_year => Date.current.year, :end_year => Date.current.year + 25,:order => [:day, :month, :year] %>
  </div>

    <%= f.hidden_field :booking_date, :value=>Time.now.strftime('%d-%b-%Y') %>
  <div class="field">
    <%= f.label :no_of_persons, "No.of Persons" %><br />
    <%= f.text_field :no_of_persons,:id=>'persons' %>
	   <script type="text/javascript">
        var persons = new LiveValidation('persons');
        
        persons.add(Validate.Numericality, {
            onlyInteger: true
        });
    </script>
  </div>
    <%= f.hidden_field :amount %>


  <div class="actions">
    <%= f.submit "Book"%>
  </div>
<% end %>

<script>
jQuery(function($) {
  $('#seva_booking_seva_id').bind('change', function() {
    var seva_id = $('#seva_booking_seva_id').val();
     $.get("/seva_bookings/get_persons", {id: seva_id},
        function(data){

        });
    return false
  })
  $('#seva_booking_gotram_id').bind('change', function() {
    if($('#seva_booking_gotram_id option:selected').text() == "Others"){
      console.log("Others");
      $('#gotram_name').show();
    }else{
		$('#gotram_name').hide();
	}
  })
});
</script>

app/views/seva_bookings/date_range_report.html.erb
<div id = 'holderSevaBookings'>
        <center/><%= link_to 'New Seva Booking', new_seva_booking_path %>
        <%= link_to 'EOD Report', {:controller=> 'seva_bookings', :action=>'eodreport'} %>
        <%= link_to 'Seva Report', {:controller=> 'seva_bookings', :action=>'date_range_report'} %>
        <%= link_to 'Date Range  Report', {:controller=> 'seva_bookings', :action=>'seva_report'}%>
        </center>
        <center>
        <br />
        <center><%= link_to 'Print Seva Report', {:action=>'date_range_report_print', :start_date=> params[:start_date]? params[:start_date]:'', :end_date => params[:end_date]? params[:end_date]:'' }  %></center>
        <br />

        <%= form_tag  do -%>
          Start Date : <%= text_field_tag 'start_date',  params[:start_date]? params[:start_date]:'' %>
          End Date : <%= text_field_tag 'end_date', params[:end_date]? params[:end_date]:'' %>
          <%= submit_tag 'Get' %>
        <% end -%>
        </center>
        <table id='listSevaBookings'>
          <thead>
          <tr>
            <th>Rcpt No</th>
            <th>Booking date</th>
            <th>Devotee name</th>
            <th>Gotram</th>
            <th>Seva</th>
            <th>Seva date</th>
            <th>No of persons</th>
            <th>Rate</th>
          </tr>
          </thead>
          <tbody>
        <% @rangereport.each do |seva_booking| %>
		<%unless seva_booking.seva.name == "Others"%>
          <tr>
            <td><%= seva_booking.reciept_number %></td>
            <td><%= seva_booking.booking_date.strftime("%d-%m-%Y") %></td>
            <td><%= seva_booking.devotee_name %></td>
            <td><%= seva_booking.gotram.name %></td>
               <td><%= seva_booking.seva.name %></td>

            <td><%= seva_booking.seva_date.strftime("%d-%m-%Y") %></td>
            <td><%= seva_booking.no_of_persons %></td>
            <td><%= seva_booking.amount %></td>
          </tr>
		  <%else%>
		  <%end%>
        <% end %>
          </tbody>
        </table>



        <script>
        $('#listSevaBookings').fixheadertable({
            caption     : 'List All Seva Bookings',
            colratio    : [50, 150,150],
            height      : 200,
            width       : 950,
            zebra       : false,
            sortable    : true,
            sortedColId : 1,
            sortType    : ['integer', 'date','string','string','string','date'],
            dateFormat  : 'm/d/Y',
            pager       : true,
            rowsPerPage : 10,
            resizeCol	: true
        });
        </script>

        <script>
	          $(function() {
		          $( "#start_date" ).datepicker({ dateFormat: 'dd-mm-yy' });
		          $( "#end_date" ).datepicker({ dateFormat: 'dd-mm-yy' });
	          });
      	</script>
</div>

app/views/seva_bookings/date_range_report_print.html.erb
<center>
    <h3>MANTRALAYAM SRI RAGAHAVENDRASWAMY MUTT, MALKAJGIRI (Branch)<h3>
        </center>
        <center>
            <h3>GENERAL SEVA REPORT<h3>
                </center>
<%if @sevas.blank?%>
<br /><br /><br /><br />
<p align="center">No Records Found.</p>
<%else%>
                <p align="left">
                    From <%= params[:start_date] %>  To <%= params[:end_date]%>
                    <p>
<table align="center" width="100%">
	<tr>
		<td width="5%">No</td>	
		<td width="20%">RECEIPT</td>
		<td width="50%">NAME</td>
		<td width="25%">GOTHRM</td>
	</tr>
</table>
<br/>
<% for seva in @sevas %>
<% unless seva.name == "Others" %>
<%= seva.name.upcase %>
<table align="center" width="100%">
	<% i = 1%>
    <% for seva_booking in seva.seva_bookings %>
		<tr>
		<td width="5%"><%= i %></td>
        <td width="20%"><%=seva_booking.reciept_number %></td>
		<td width="50%"><%=seva_booking.devotee_name %></td>
		<td width="25%"><%=seva_booking.gotram.name %></td>
		</tr>
		<% i = i + 1%>
    <% end %>
<%else %>
<%end %>
</table>
<br/>
<% end %>
<%end%>

app/views/seva_bookings/edit.html.erb
<h3>Editing Seva Booking</h3>
<hr />

<%= render 'form' %>

<%= link_to 'Show', @seva_booking %> |
<%= link_to 'Back', seva_bookings_path %>

app/views/seva_bookings/grt.html.erb
<h3>General Reciept</h3>
<hr/>

<%= form_for(@seva_booking) do |f| %>
  <% if @seva_booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@seva_booking.errors.count, "error") %> prohibited this seva_booking from being saved:</h2>

      <ul>
      <% @seva_booking.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :devotee_name, "Devotee Name" %><br />
     <%= f.text_field :devotee_name,:id=>'dname',:onChange=>"capitalizeMe(this)" %>
	<script type="text/javascript">
				var dname = new LiveValidation('dname');
				dname.add(Validate.Presence)
	</script>
  </div>
  <div class="field">
    <%= f.label :gotram %><br />
    <%= collection_select(:seva_booking, :gotram_id, @gotrams, :id, :name, :prompt=> "Select Gotram") %>
			<script type="text/javascript">
				var seva_booking_gotram_id = new LiveValidation('seva_booking_gotram_id');
				seva_booking_gotram_id.add(Validate.Presence)
	</script>
  </div>
    <div class="field" style="display:none" id="gotram_name">
    <%= f.label :gotram %><br />
    <%= f.text_field :gotram_name,:onChange=>"capitalizeMe(this)" %>
  </div>
  <div class="field">
    <%= f.label :seva %><br />
    <%= collection_select(:seva_booking, :seva_id, @sevas, :id, :name, :prompt=> "Select Seva") %>
			<script type="text/javascript">
				var seva_booking_seva_id = new LiveValidation('seva_booking_seva_id');
				seva_booking_seva_id.add(Validate.Presence)
	</script>
  </div>
  <div class="field" style="display:none" id="seva_name">
    <%= f.label :seva %><br />
    <%= f.text_field :seva_name,:onChange=>"capitalizeMe(this)" %>
  </div>
  <div class="field">
    <%= f.label :seva_date, "Seva Date" %><br />
    <%= f.date_select :seva_date,:start_year => Date.current.year, :end_year => Date.current.year + 25,:order => [:day, :month, :year] %>
  </div>
   <%= f.hidden_field :booking_date, :value=>Time.now.strftime('%d-%b-%Y') %>
  <div class="field">
    <%= f.label :no_of_persons, "No.of Persons" %><br />
    <%= f.text_field :no_of_persons,:id=>'persons' %>
			<script type="text/javascript">
				var persons = new LiveValidation('persons');
				
				persons.add(Validate.Numericality, {
                    onlyInteger: true
                });
	</script>
  </div>

  <div class="field"  id="amount">
    <%= f.label :amount %><br />
    <%= f.text_field :amount,:id=>'ramount' %>
		<script type="text/javascript">
				var ramount = new LiveValidation('ramount');
				ramount.add(Validate.Presence);
				ramount.add(Validate.Numericality, {
                    onlyInteger: true
                });
	</script>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<%= link_to 'Back', seva_bookings_path %>

<script>
jQuery(function($) {
  $('#seva_booking_seva_id').bind('change', function() {
    if($('#seva_booking_seva_id option:selected').text() == "Others"){
      $('#seva_name').show();
      $('#amount').show();
    }else
	{ $('#seva_name').hide();}
  })
  $('#seva_booking_gotram_id').bind('change', function() {
    if($('#seva_booking_gotram_id option:selected').text() == "Others"){
      $('#gotram_name').show();
    }
	else
	{$('#gotram_name').hide();}
  })
});
</script>

app/views/seva_bookings/index.html.erb
<div id = 'holderSevaBookings'>
	<center/>
		<%= link_to 'New Seva Booking', new_seva_booking_path %>
		<%= link_to 'EOD Report', {:controller=> 'seva_bookings', :action=>'eodreport'} %>
		<%= link_to 'Seva Report', {:controller=> 'seva_bookings', :action=>'date_range_report'} %>
		<%= link_to 'Date Range Report',{:controller=> 'seva_bookings', :action=>'seva_report'} %>
	</center>
	<br />

	<table id='listSevaBookings'>
		<thead>
			<tr>
				<th>R.No</th>
				<th>Booking Date</th>
				<th>Devotee Name</th>
				<th>Gotram</th>
				<th>Seva</th>
				<th>Seva Date</th>
				<th>Persons</th>
				<th>Rate</th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<% @seva_bookings.each do |seva_booking| %>
			<tr>
				<td><%= seva_booking.reciept_number %></td>
				<td><%= seva_booking.booking_date.strftime('%d-%m-%Y') %></td>
				<td><%= seva_booking.devotee_name %></td>
				<%if seva_booking.gotram.name == "Others"%>
				<td><%= seva_booking.gotram_name %>(O)</td>
				<%else%>
				<td><%= seva_booking.gotram.name %></td>
				<%end%>
				<% if seva_booking.seva.name == "Others" -%>
				<td><%= seva_booking.seva_name %>(O)</td>
				<% else -%>
				<td><%= seva_booking.seva.name %></td>
				<% end -%>

				<td><%= seva_booking.seva_date.strftime('%d-%m-%Y') %></td>
				<td><%= seva_booking.no_of_persons %></td>
				<td><%= seva_booking.amount %></td>
				<td><%= link_to 'View', seva_booking %>
				<%= link_to 'Edit', edit_seva_booking_path(seva_booking) %>
<!--				<%= link_to 'Destroy', seva_booking, :confirm => 'Are you sure?', :method => :delete %>-->
				</td>
			</tr>
			<% end %>
		</tbody>
	</table>
	<script>$('#listSevaBookings').fixheadertable({
			caption     : 'List of All Seva Bookings',
			colratio    : [20, 150,150],
			height      : 200,
			width       : 950,
			zebra       : false,
			sortable    : true,
			sortedColId : 1,
			sortType    : ['string', 'date','string','string','string','date'],
			dateFormat  : 'd/m/Y',
			pager       : true,
			rowsPerPage : 10,
			resizeCol	: true
		});</script>
</div>

app/views/seva_bookings/new.html.erb
<h3>New Seva Booking</h3>
<hr/>

<%= render 'form' %>

<%= link_to 'Back', seva_bookings_path %>

app/views/seva_bookings/othereodreport.html.erb
<div id = 'holderSevaBookings'>
        <center/><%= link_to 'New Seva Booking', new_seva_booking_path %>
        <%= link_to 'EOD Report', {:controller=> 'seva_bookings', :action=>'eodreport'} %>
        <%= link_to 'Seva Report', {:controller=> 'seva_bookings', :action=>'date_range_report'} %>
        <%= link_to 'Date Range Report', {:controller=> 'seva_bookings', :action=>'seva_report'}%>
        </center>
        <br />
        <center><%= link_to 'Print Other EOD Report', {:action=>'othereodreport_print'}  %></center>
        <br />
		
        <table id='listSevaBookings'>
          <thead>
          <tr>
            <th>Rcpt No</th>
            <th>Booking date</th>
            <th>Devotee name</th>
            <th>Gotram</th>
            <th>Seva</th>
            <th>Seva date</th>
            <th>No of persons</th>
            <th>Rate </th>
            <th></th>
          </tr>
          </thead>
          <tbody>
        <% @eodreport.each do |seva_booking| %>
          <tr>
            <td><%= seva_booking.reciept_number %></td>
            <td><%= seva_booking.booking_date.strftime("%d-%m-%Y") %></td>
            <td><%= seva_booking.devotee_name %></td>

            	<%if seva_booking.gotram.name == "Others"%>
				<td>
				<%= seva_booking.gotram_name %>
				</td>
				<%else%>
				<td>
				<%= seva_booking.gotram.name %>
				</td>
				<%end%>
             <td><%= seva_booking.seva_name %>(O)</td>
            <td><%= seva_booking.seva_date.strftime("%d-%m-%Y") %></td>
            <td><%= seva_booking.no_of_persons %></td>
            <td><%= seva_booking.amount %></td>
            <td><%= link_to 'Show', seva_booking %>
            <%= link_to 'Edit', edit_seva_booking_path(seva_booking) %>
            <%= link_to 'Destroy', seva_booking, :confirm => 'Are you sure?', :method => :delete %>
          </tr>
        <% end %>
          </tbody>
        </table>



        <script>
        $('#listSevaBookings').fixheadertable({
            caption     : 'Others EOD Report for <%= Date.today.strftime("%d-%m-%Y")%>',
            colratio    : [50, 150,150],
            height      : 200,
            width       : 950,
            zebra       : false,
            sortable    : true,
            sortedColId : 1,
            sortType    : ['integer', 'date','string','string','string','date'],
            dateFormat  : 'm/d/Y',
            pager       : true,
            rowsPerPage : 10,
            resizeCol	: true
        });
        </script>		
</div>

app/views/seva_bookings/othereodreport_print.html.erb
<center>
    <h3>MANTRALAYAM SRI RAGAHAVENDRASWAMY MUTT, MALKAJGIRI (Branch)<h3>
        </center>
        <center>
            <h3>ACCOUNT SUMMARY REPORT (OTHERS)<h3>
                </center>

                <p align="left">
                    For <%= Date.today.strftime("%d-%m-%Y") %>
                    <p>
      
        <table align="center" width="100%" >
          <thead>
          <tr>
            <td width="10%">Rec. No</td>
            <td width="25%">Particulars</td>
            <td width="50%">Description</td>
            <td width="15%">Amount (Rs.)</td>
          </tr>
          </thead>
          <tbody>
        <% @eodreport.each do |seva_booking| %>
          <tr>
            <td><%= seva_booking.reciept_number %></td>
            <td><%= seva_booking.devotee_name %></td>
            <td><%= seva_booking.seva_name %></td>
            <td align="right"><%= seva_booking.amount %></td>
          </tr>
        <% end %>
		<tr>
			<td colspan="3"align="right">Total</td>
			<td align="right"><%= @eodreport.sum(&:amount)%></td>
		</tr>
          </tbody>
        </table>
        

app/views/seva_bookings/print.html.erb
<html>
<head>
</head>
<body>
<br>
<br>
<br>
<p align="right">Booking Date:<%= @seva_booking.booking_date.strftime("%d-%m-%Y") %></p>
<style>
table{
	font: 11px;
}
</style>

<table>
	<tr>
		<td>Receipt No</td>
		<td>:&nbsp;</td>
		<td><%= @seva_booking.reciept_number %></td>
	</tr>
	<tr>
		<td>Name</td>
		<td>:&nbsp;</td>
		<td><%= @seva_booking.devotee_name %></td>
	</tr>
	<tr>
		<td>Gothram</td>
		<td>:&nbsp;</td>
		<td><%= @seva_booking.gotram.name.capitalize %></td>
	</tr>
	<tr>
		<td>Seva</td>
		<td>:&nbsp;</td>
				<% if @seva_booking.seva.name =="Others" -%>
		<td>
		<%= @seva_booking.seva_name %>
		</td>
		<% else -%>
		<td>
		<%= @seva_booking.seva.name %>
		</td>
		<% end -%>
	</tr>
	<tr>
		<td>Seva Date</td>
		<td>:&nbsp;</td>
		<td><%= @seva_booking.seva_date.strftime("%d-%m-%Y") %></td>
	</tr>

	<tr>
		<td>Amount</td>
		<td>:&nbsp;</td>
		<td>Rs.<%= @seva_booking.amount %> /-</td> 
	</tr>
	<tr>
		<td colspan="2">
		<td>(In Words: Rupees <%= @seva_booking.amount.to_english.capitalize %> only.)</td>
	</tr>	
</table>
</body>

app/views/seva_bookings/save_reciept.js.erb
$("#reciept_holder").hide();

app/views/seva_bookings/show.html.erb
<p id="notice">
	<%= notice %>
</p>
<p>
	<b>Devotee Name:</b>
	<%= @seva_booking.devotee_name %>
</p>
<p>
	<b>Gotram:</b>
	<% if @seva_booking.gotram.name == "Others"%>
	<%= @seva_booking.gotram_name%>
	<%else%>
	<%= @seva_booking.gotram.name %>
	<%end%>
</p>
<p>
	<b>Seva:</b>
	<% if @seva_booking.seva.name == "Others"%>
	<%= @seva_booking.seva_name%>
	<% else%>
	<%= @seva_booking.seva.name %>
	<%end%>
</p>
<p>
	<b>Seva Date:</b>
	<%= @seva_booking.seva_date.strftime('%d-%m-%Y') %>
</p>
<p>
	<b>Booking Date:</b>
	<%= @seva_booking.booking_date.strftime('%d-%m-%Y') %>
</p>
<p>
	<b>No of Persons:</b>
	<%= @seva_booking.no_of_persons %>
</p>
<% if @seva_booking.reciept_number? -%>
<p>
	<b>Reciept Number</b>
	<%= @seva_booking.reciept_number %>
</p>
<% else -%>

<% end -%>

<br />
<%= link_to 'Edit', edit_seva_booking_path(@seva_booking) %> &nbsp;
<%= link_to 'Back', seva_bookings_path %> &nbsp;
<%= link_to "Print Invoice", {:action=>'print'}%>