config/routes.rb
Srmatham::Application.routes.draw do
  get "home/index"

  resources :seva_bookings do
    get :eodreport, :on=>:collection
    get :eodreport_print, :on=>:collection
    get :date_range_report, :on=>:collection
    get :date_range_report_print, :on=> :collection
    get :seva_report, :on=>:collection
    get :seva_report_print, :on=>:collection
    get :get_persons, :on=>:collection
    get :print, :on => :member
    post :save_reciept
    get :grt, :on=>:collection
    get :othereodreport, :on=>:collection
    get :othereodreport_print, :on=>:collection
end

  resources :sevas do
    get :sevareport, :on=>:collection
  end

  resources :gotrams

  root :to => "home#index"

   match ':controller(/:action(/:id(.:format)))'
end

app/models/seva.rb
class Seva < ActiveRecord::Base
  has_many :seva_bookings,:order=>:reciept_number,:dependent=>:destroy
  
  validates_uniqueness_of :short_code, :name
end

app/controllers/sevas_controller.rb
class SevasController < ApplicationController

  def index
    @sevas = Seva.order("name ASC")

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @sevas }
    end
  end

  def show
    @seva = Seva.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @seva }
    end
  end

  def new
    @seva = Seva.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @seva }
    end
  end

  def edit
    @seva = Seva.find(params[:id])
  end

  def create
    @seva = Seva.new(params[:seva])
   
    @seva.short_code = params[:seva][:short_code].upcase
    respond_to do |format|
      if @seva.save
        format.html { redirect_to(@seva, :notice => 'Seva was successfully created.') }
        format.xml  { render :xml => @seva, :status => :created, :location => @seva }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @seva.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @seva = Seva.find(params[:id])

    respond_to do |format|
      if @seva.update_attributes(params[:seva])
        format.html { redirect_to(@seva, :notice => 'Seva was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @seva.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @seva = Seva.find(params[:id])
    @seva.destroy

    respond_to do |format|
      format.html { redirect_to(sevas_url) }
      format.xml  { head :ok }
    end
  end

  def sevareport
    @sevas=Seva.order("name ASC")
    html = render_to_string :layout => false 
    kit = PDFKit.new(html)
    kit.stylesheets << RAILS_ROOT + '/public/stylesheets/styles.css' 
    send_data(kit.to_pdf, :filename => "Seva.pdf", :type => 'application/pdf')
  end

end

app/helpers/sevas_helper.rb
module SevasHelper
end

app/views/sevas/_form.html.erb
<%= form_for(@seva) do |f| %>
<% if @seva.errors.any? %>
<div id="error_explanation">
    <h2><%= pluralize(@seva.errors.count, "error") %>prohibited this seva from being saved:</h2>
    <ul>
        <% @seva.errors.full_messages.each do |msg| %>
        <li>
            <%= msg %>
        </li>
        <% end %>
    </ul>
</div>
<% end %>
<div class="field">
    <%= f.label :name %>
    <br/>
    <%= f.text_field :name,:id=>'dname',:onChange=>"capitalizeMe(this)" %>
    <script type="text/javascript">
        var dname = new LiveValidation('dname');
        dname.add(Validate.Presence)
    </script>
</div>
<div class="field">
    <%= f.label :name, "Short Name (Max. 3 Characters)" %>
    <br/>
    <%= f.text_field :short_code,:id=>'cname' %>
    <script type="text/javascript">
        var cname = new LiveValidation('cname');
        cname.add(Validate.Presence);
		cname.add( Validate.Length, { is: 3 } );
    </script>
</div>
<div class="field">
    <%= f.label :description %>
    <br/>
    <%= f.text_area :description,:cols => 30, :rows => 5 %>
</div>
<div class="field">
    <%= f.label :rate %>
    <br/>
    <%= f.text_field :rate,:id=>'ramount' %>
    <script type="text/javascript">
        var ramount = new LiveValidation('ramount');
        ramount.add(Validate.Presence);
        ramount.add(Validate.Numericality, {
            onlyInteger: true
        });
    </script>
</div>
<div class="field">
    <%= f.label :maximum_number_of_persons,"Maximum Number of Persons" %>
    <br/>
    <%= f.text_field :max_persons,:id=>'persons' %>
    <script type="text/javascript">
        var persons = new LiveValidation('persons');
        
        persons.add(Validate.Numericality, {
            onlyInteger: true
        });
    </script>
</div>
<div class="actions">
    <%= f.submit %>
</div>
<% end %>

app/views/sevas/edit.html.erb
<h3>Edit Seva</h3>
<hr />

<%= render 'form' %>

<%= link_to 'Show', @seva %> 
<%= link_to 'Back', sevas_path %>

app/views/sevas/index.html.erb
<center><%= link_to 'New Seva', new_seva_path %>
<%= link_to 'Print Seva Report', :action=>'sevareport' %>
</center>
<br />
<center>
<table id ="listSevas">
  <thead>
  <tr>
    <th>Name</th>
    <th>Description</th>
	<th>Short Name</th>
    <th>Rate</th>
    <th>Persons</th>
    <th></th>
    <th></th>
  </tr>
  </thead>
  <tbody>
<% @sevas.each do |seva| %>
  <tr>
    <td><%= seva.name %></td>
    <td><%= seva.description %></td>
	<td><%= seva.short_code %></td>
    <td><%= seva.rate.to_i %></td>
    <td><%= seva.max_persons %></td>
    <td><%= link_to 'Show', seva %></td>
    <td><%= link_to 'Edit', edit_seva_path(seva) %></td>
<!--     <td><%= link_to 'Destroy', seva, :confirm => 'Are you sure?', :method => :delete %></td> -->
  </tr>
<% end %>
</tbody>
</table>
</center>
<script>
$('#listSevas').fixheadertable({
    caption     : 'List of Sevas',
    colratio    : [150, 650],
    height      : 200,
    width       : 800,
    zebra       : false,
    sortable    : true,
    sortedColId : 1,
    sortType    : ['string', 'string'],
    dateFormat  : 'm/d/Y',
    pager       : true,
    rowsPerPage : 10,
    resizeCol	: true
});
</script>

app/views/sevas/new.html.erb
<h3>New Seva</h3>
<hr />

<%= render 'form' %>

<%= link_to 'Back', sevas_path %>

app/views/sevas/sevareport.html.erb
<center>
    <h3>MANTRALAYAM SRI RAGAHAVENDRASWAMY MUTT, MALKAJGIRI (Branch)<h3>
        </center>
        <center>
            <h3>SEVA REPORT<h3>
                </center>
      
<table align="center" width="100%" >
  <thead>
  <tr>
    <th scope="col">Name</th>
	<th scope="col">Short Code</th>
    <th scope="col"> Rate</th>
    <th scope="col">Persons</th>
  </tr>
  </thead>
  <tbody>
<% @sevas.each do |seva| %>
<% unless seva.name == "Others"%>
  <tr>
    <td><%= seva.name %></td>
	<td><%= seva.short_code %></td>
    <td align="right"><%= seva.rate.to_i %></td>
    <td align="right"><%= seva.max_persons %></td>
  </tr>
 <%else%>
 <%end%>
<% end %>
</tbody>
</table>

app/views/sevas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @seva.name %>
</p>
<p>
  <b>Short Name:</b>
  <%= @seva.short_code %>
</p>
<p>
  <b>Description:</b>
  <%= @seva.description %>
</p>

<p>
  <b>Rate:</b>
  Rs.<%= @seva.rate %>
</p>

<p>
  <b>Maximum Number of Persons</b>
  Rs.<%= @seva.max_persons %>
</p>


<%= link_to 'Edit', edit_seva_path(@seva) %> 
<%= link_to 'Back', sevas_path %>

app/views/sevas/show.js.erb
window.open (<%= seva_url(@seva) %>, "mywindow","width=600,height=600");