config/routes.rb
Srmatham::Application.routes.draw do
  get "home/index"

  resources :seva_bookings do
    get :eodreport, :on=>:collection
    get :eodreport_print, :on=>:collection
    get :date_range_report, :on=>:collection
    get :date_range_report_print, :on=> :collection
    get :seva_report, :on=>:collection
    get :seva_report_print, :on=>:collection
    get :get_persons, :on=>:collection
    get :print, :on => :member
    post :save_reciept
    get :grt, :on=>:collection
    get :othereodreport, :on=>:collection
    get :othereodreport_print, :on=>:collection
end

  resources :sevas do
    get :sevareport, :on=>:collection
  end

  resources :gotrams

  root :to => "home#index"

   match ':controller(/:action(/:id(.:format)))'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sri Raghavendra Swamy Matham, Malkajgiri</title>
  <%= stylesheet_link_tag 'base','jquery-ui-1.8.11.custom','scaffold','live_validation',:media => "all" %>
  <%= javascript_include_tag 'jquery-1.5.2.min','jquery-ui-1.8.11.custom.min','jquery.fixheadertable','rails','livevalidation_standalone.compressed','application' %>
  <%= csrf_meta_tag %>
</head>
<body>
<div class='container'>
  <div class='column span-12'>
    <center><h5>SRI MOOLARAMO VIJAYATE</h5></center>
  </div>
  <div class='column last span-12'>
    <center><h5>SRI GURURAJO VIJAYATHE</h5></center>
  </div>
</div>
<div class='container'>
  <center><h3>JAGADGURU SRIMAN MADHWACHARYA MOOLA MAHA SAMSTHANAM</h3> </center>
</div>
<div class='container'>
  <center><h2>MANTRALAYAM SRI RAGAHAVENDRASWAMY MUTT, MALKAJGIRI (Branch)</h2></center>
</div>

<div class='container'>
  <center>
    <%= link_to 'Home', '/home/index'  %>
    <%= link_to 'Seva Booking', new_seva_booking_path %>
    <%= link_to 'GRT', '/seva_bookings/grt'  %>
    <%= link_to 'List Seva Bookings', seva_bookings_path %>
    <%= link_to 'List All Sevas', sevas_path %>
    <%= link_to 'List All Gotras', gotrams_path %>
    <%= link_to 'Inventory' ,'/#' %>
    <%= link_to 'Donations', '/#' %>
  </center>
</div>

<div class='container bodyContent'>
  <%= yield %>
</div>
</body>
</html>